before_install:
  - brew update
  - brew upgrade xctool
  - cd $TRAVIS_BUILD_DIR/LigerTestApp
language: objective-c
install: ''
xcode_workspace: Liger.xcworkspace
xcode_scheme: Liger
after_success:
  - cd $TRAVIS_BUILD_DIR
  - ./ci/release.sh
